"use client";

import { useEffect, useState, useCallback } from "react";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import {
  ArrowLeft,
  Plus,
  Save,
  Trash2,
  GripVertical,
  Video,
  FileText,
  HelpCircle,
  MoreVertical,
  Edit,
  X,
  Check,
  Upload,
  Loader2,
  Image as ImageIcon,
  Copy,
  FileVideo,
  Settings,
} from "lucide-react";
import { Reorder } from "framer-motion";
import { AdminLayout } from "@/components/admin/layout";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Separator } from "@/components/ui/separator";
import { courseService } from "@/services/course.service";
import { lessonService } from "@/services/lesson.service";
import { lessonItemService } from "@/services/lesson-item.service";
import { mediaStreamingService, UploadProgress, UploadResult } from "@/services/media-streaming.service";
import { contentService, LessonItemType as ContentLessonItemType } from "@/services/content.service";
import { Course } from "@/models/course.model";
import { Lesson } from "@/models/lesson.model";
import { LessonItem } from "@/models/lesson-item.model";
import { cn } from "@/lib/utils";
import { PuzzleLoader } from "@/components/PuzzleLoader";
import { Progress } from "@/components/ui/progress";
import { useToast } from "@/hooks/use-toast";

type LessonItemType = 'video' | 'text' | 'question' | 'rich-content';

interface CourseLesson {
  id: string;
  title: string;
  description?: string;
  order: number;
  items: LessonItem[];
}

export default function LessonsPage() {
  const params = useParams();
  const router = useRouter();
  const searchParams = useSearchParams();
  const courseId = params.courseId as string;
  const selectedLessonId = searchParams.get("lessonId");

  const [currentCourse, setCurrentCourse] = useState<Course | null>(null);
  const [courseLessons, setCourseLessons] = useState<CourseLesson[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  const [selectedLesson, setSelectedLesson] = useState<CourseLesson | null>(null);
  const [isEditingLesson, setIsEditingLesson] = useState(false);
  const [lessonEditForm, setLessonEditForm] = useState({ title: "", description: "" });
  const [addItemDialogOpen, setAddItemDialogOpen] = useState(false);
  const [selectedItemType, setSelectedItemType] = useState<LessonItemType | null>(null);
  const [deleteItemId, setDeleteItemId] = useState<string | null>(null);
  
  // Form states for different item types
  const [itemName, setItemName] = useState("");
  const [videoUrl, setVideoUrl] = useState("");
  const [videoDuration, setVideoDuration] = useState(0);
  const [richTextContent, setRichTextContent] = useState("");
  const [questionText, setQuestionText] = useState("");
  const [questionOptions, setQuestionOptions] = useState<string[]>(["", "", "", ""]);
  const [correctOptionIndex, setCorrectOptionIndex] = useState(0);

  // Video upload states
  const [videoFile, setVideoFile] = useState<File | null>(null);
  const [videoPreviewUrl, setVideoPreviewUrl] = useState<string | null>(null);
  const [videoUploadState, setVideoUploadState] = useState<'idle' | 'uploading' | 'processing' | 'complete' | 'error'>('idle');
  const [videoUploadProgress, setVideoUploadProgress] = useState(0);
  const [videoUploadResult, setVideoUploadResult] = useState<UploadResult | null>(null);
  const [thumbnailFile, setThumbnailFile] = useState<File | null>(null);
  const [thumbnailPreviewUrl, setThumbnailPreviewUrl] = useState<string | null>(null);
  const [thumbnailUploadResult, setThumbnailUploadResult] = useState<UploadResult | null>(null);
  const [autoGeneratedThumbnail, setAutoGeneratedThumbnail] = useState<string | null>(null);
  const [thumbnailMode, setThumbnailMode] = useState<'upload' | 'auto' | 'none'>('auto');

  const { toast } = useToast();

  const loadCourseData = useCallback(async () => {
    setIsLoading(true);
    try {
      const [course, rawLessons] = await Promise.all([
        courseService.getCourseById(courseId),
        lessonService.getLessonsByCourse(courseId),
      ]);
      
      setCurrentCourse(course);
      
      const lessonsWithItems: CourseLesson[] = await Promise.all(
        rawLessons.map(async (lesson) => {
          const items = await lessonItemService.getItemsByLesson(lesson.id);
          return {
            id: lesson.id,
            title: lesson.title,
            description: lesson.description,
            order: lesson.order || 0,
            items,
          };
        })
      );
      
      setCourseLessons(lessonsWithItems);
    } catch (error) {
      console.error('Failed to load course:', error);
    } finally {
      setIsLoading(false);
    }
  }, [courseId]);

  useEffect(() => {
    loadCourseData();
  }, [loadCourseData]);

  useEffect(() => {
    if (courseLessons.length > 0 && selectedLessonId) {
      const lesson = courseLessons.find((l) => l.id === selectedLessonId);
      setSelectedLesson(lesson || null);
      if (lesson) {
        setLessonEditForm({ title: lesson.title, description: lesson.description || "" });
      }
    }
  }, [courseLessons, selectedLessonId]);

  if (isLoading || !currentCourse) {
    return (
      <AdminLayout>
        <PuzzleLoader />
      </AdminLayout>
    );
  }

  const handleSaveLesson = async () => {
    if (!selectedLesson) return;
    try {
      await lessonService.updateLesson(selectedLesson.id, {
        title: lessonEditForm.title,
      });
      await loadCourseData();
      setIsEditingLesson(false);
    } catch (error) {
      console.error('Failed to update lesson:', error);
    }
  };

  const handleDeleteLesson = async () => {
    if (!selectedLesson) return;
    try {
      await lessonService.deleteLesson(selectedLesson.id);
      router.push(`/admin/courses/${courseId}`);
    } catch (error) {
      console.error('Failed to delete lesson:', error);
    }
  };

  const resetItemForm = () => {
    setItemName("");
    setVideoUrl("");
    setVideoDuration(0);
    setRichTextContent("");
    setQuestionText("");
    setQuestionOptions(["", "", "", ""]);
    setCorrectOptionIndex(0);
    // Reset video upload states
    if (videoPreviewUrl) URL.revokeObjectURL(videoPreviewUrl);
    if (thumbnailPreviewUrl) URL.revokeObjectURL(thumbnailPreviewUrl);
    if (autoGeneratedThumbnail) URL.revokeObjectURL(autoGeneratedThumbnail);
    setVideoFile(null);
    setVideoPreviewUrl(null);
    setVideoUploadState('idle');
    setVideoUploadProgress(0);
    setVideoUploadResult(null);
    setThumbnailFile(null);
    setThumbnailPreviewUrl(null);
    setThumbnailUploadResult(null);
    setAutoGeneratedThumbnail(null);
    setThumbnailMode('auto');
  };

  const handleVideoFileSelect = async (file: File) => {
    if (!mediaStreamingService.isValidVideoFile(file)) {
      toast({
        title: "Invalid file type",
        description: "Please select a valid video file (MP4, WebM, etc.)",
        variant: "destructive",
      });
      return;
    }

    setVideoFile(file);
    setVideoPreviewUrl(URL.createObjectURL(file));

    // Auto-fill name from filename if empty
    const titleFromFile = file.name.replace(/\.[^/.]+$/, "").replace(/[_-]/g, " ");
    if (!itemName) {
      setItemName(titleFromFile);
    }

    // Get video metadata and start upload
    setVideoUploadState('uploading');
    setVideoUploadProgress(0);

    try {
      const result = await mediaStreamingService.uploadVideo(file, (progress: UploadProgress) => {
        setVideoUploadProgress(progress.percentage);
      });

      setVideoUploadState('processing');

      // Generate auto thumbnail
      const thumbnailBlob = await mediaStreamingService.generateThumbnailFromVideo(file, 1);
      if (thumbnailBlob) {
        const thumbnailUrl = URL.createObjectURL(thumbnailBlob);
        setAutoGeneratedThumbnail(thumbnailUrl);
      }

      setVideoUploadResult(result);
      setVideoUrl(result.url);
      setVideoDuration(result.duration || 0);
      setVideoUploadState('complete');
    } catch (error) {
      setVideoUploadState('error');
      toast({
        title: "Upload failed",
        description: "Failed to upload video. Please try again.",
        variant: "destructive",
      });
    }
  };

  const handleThumbnailFileSelect = async (file: File) => {
    if (!mediaStreamingService.isValidImageFile(file)) {
      toast({
        title: "Invalid file type",
        description: "Please select a valid image file (JPG, PNG, etc.)",
        variant: "destructive",
      });
      return;
    }

    setThumbnailFile(file);
    setThumbnailPreviewUrl(URL.createObjectURL(file));
    setThumbnailMode('upload');

    try {
      const result = await mediaStreamingService.uploadThumbnail(file);
      setThumbnailUploadResult(result);
    } catch (error) {
      toast({
        title: "Upload failed",
        description: "Failed to upload thumbnail. Please try again.",
        variant: "destructive",
      });
    }
  };

  const removeVideoFile = () => {
    if (videoPreviewUrl) URL.revokeObjectURL(videoPreviewUrl);
    if (autoGeneratedThumbnail) URL.revokeObjectURL(autoGeneratedThumbnail);
    setVideoFile(null);
    setVideoPreviewUrl(null);
    setVideoUploadState('idle');
    setVideoUploadProgress(0);
    setVideoUploadResult(null);
    setVideoUrl("");
    setVideoDuration(0);
    setAutoGeneratedThumbnail(null);
  };

  const handleCreateItem = async () => {
    if (!selectedLesson || !selectedItemType || !itemName.trim()) return;
    
    try {
      const typeMap = { 'video': 0, 'text': 1, 'rich-content': 1, 'question': 2 };
      let contentId = "";
      let duration = 0;

      if (selectedItemType === "video") {
        let thumbnailUrl: string | undefined;
        if (thumbnailMode === 'upload' && thumbnailUploadResult?.url) {
          thumbnailUrl = thumbnailUploadResult.url;
        } else if (thumbnailMode === 'auto' && autoGeneratedThumbnail) {
          // Upload auto-generated thumbnail
          const response = await fetch(autoGeneratedThumbnail);
          const blob = await response.blob();
          const file = new File([blob], 'auto-thumbnail.jpg', { type: 'image/jpeg' });
          const result = await mediaStreamingService.uploadThumbnail(file);
          thumbnailUrl = result.url;
        }
        // Create video content first
        const contentResult = await contentService.createContent({
          type: ContentLessonItemType.Video,
          video: {
            title: itemName,
            url: videoUrl,
            thumbnailUrl: thumbnailUrl,
            durationInSeconds: videoDuration,
          },
        });
        contentId = contentResult.id;
        duration = videoDuration;
      } else if (selectedItemType === "rich-content" || selectedItemType === "text") {
        // Create rich text content first
        const contentResult = await contentService.createContent({
          type: ContentLessonItemType.RichText,
          richText: {
            title: itemName,
            html: richTextContent,
          },
        });
        contentId = contentResult.id;
      } else if (selectedItemType === "question") {
        // Create quiz content first
        const contentResult = await contentService.createContent({
          type: ContentLessonItemType.Quiz,
          quiz: {
            title: itemName,
            questions: [{
              questionText: questionText,
              options: questionOptions.filter(opt => opt.trim()),
              correctAnswerIndex: correctOptionIndex,
            }],
          },
        });
        contentId = contentResult.id;
      }

      await lessonItemService.createLessonItem({
        name: itemName,
        contentId,
        type: typeMap[selectedItemType],
        lessonId: selectedLesson.id,
        durationInSeconds: duration,
      });
      
      await loadCourseData();
      setAddItemDialogOpen(false);
      setSelectedItemType(null);
      resetItemForm();
    } catch (error) {
      console.error('Failed to create item:', error);
    }
  };

  const handleDeleteItem = async () => {
    if (!selectedLesson || !deleteItemId) return;
    try {
      await lessonItemService.deleteLessonItem(deleteItemId);
      await loadCourseData();
      setDeleteItemId(null);
    } catch (error) {
      console.error('Failed to delete item:', error);
    }
  };

  const handleReorderItems = (newItems: LessonItem[]) => {
    if (!selectedLesson) return;
    // TODO: Backend doesn't support reordering yet
    console.warn('Reordering not supported by backend yet');
  };

  const getItemIcon = (type: string) => {
    switch (type) {
      case "video":
        return <Video className="h-4 w-4 text-primary" />;
      case "text":
      case "rich-content":
        return <FileText className="h-4 w-4 text-secondary" />;
      case "question":
        return <HelpCircle className="h-4 w-4 text-warning" />;
      default:
        return <FileText className="h-4 w-4" />;
    }
  };

  const getContentInfo = (item: LessonItem) => {
    if (!item.content) return 'No content';
    if (typeof item.content === 'string') {
      return item.content.slice(0, 60) + (item.content.length > 60 ? '...' : '');
    }
    // Handle object content (video, quiz, etc.)
    const contentObj = item.content as Record<string, unknown>;
    if (contentObj.title) return String(contentObj.title);
    if (contentObj.url) return String(contentObj.url).slice(0, 60);
    return 'Content attached';
  };

  const sortedLessons = [...courseLessons].sort((a, b) => a.order - b.order);

  return (
    <AdminLayout
      breadcrumbs={[
        { label: "Courses", href: "/admin/courses" },
        { label: currentCourse.title, href: `/admin/courses/${courseId}` },
        { label: "Lessons" },
      ]}
    >
      <div className="flex h-[calc(100vh-4rem)]">
        {/* Lesson Sidebar */}
        <div className="w-72 border-r bg-muted/30 flex flex-col">
          <div className="p-4 border-b">
            <h2 className="font-semibold">Lessons</h2>
            <p className="text-xs text-muted-foreground">
              {currentCourse.lessons.length} lessons
            </p>
          </div>
          <ScrollArea className="flex-1">
            <div className="p-2">
              {sortedLessons.map((lesson) => (
                <Link
                  key={lesson.id}
                  href={`/admin/courses/${courseId}/lessons?lessonId=${lesson.id}`}
                  className={cn(
                    "flex items-center gap-2 p-3 rounded-lg mb-1 transition-colors",
                    selectedLessonId === lesson.id
                      ? "bg-primary text-primary-foreground"
                      : "hover:bg-muted"
                  )}
                >
                  <span className="text-xs font-medium w-5">{lesson.order}</span>
                  <span className="flex-1 truncate text-sm">{lesson.title}</span>
                  <Badge
                    variant={selectedLessonId === lesson.id ? "secondary" : "outline"}
                    className="text-xs"
                  >
                    {lesson.items.length}
                  </Badge>
                </Link>
              ))}
            </div>
          </ScrollArea>
          <div className="p-2 border-t">
            <Button
              variant="outline"
              size="sm"
              className="w-full"
              onClick={() => router.push(`/admin/courses/${courseId}`)}
            >
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Course
            </Button>
          </div>
        </div>

        {/* Main Content */}
        <div className="flex-1 overflow-auto">
          {selectedLesson ? (
            <div className="p-6 space-y-6">
              {/* Lesson Header */}
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  {isEditingLesson ? (
                    <div className="space-y-3">
                      <Input
                        value={lessonEditForm.title}
                        onChange={(e) =>
                          setLessonEditForm((prev) => ({ ...prev, title: e.target.value }))
                        }
                        className="text-xl font-bold"
                      />
                      <Textarea
                        value={lessonEditForm.description}
                        onChange={(e) =>
                          setLessonEditForm((prev) => ({ ...prev, description: e.target.value }))
                        }
                        placeholder="Lesson description..."
                      />
                      <div className="flex gap-2">
                        <Button size="sm" onClick={handleSaveLesson}>
                          <Save className="mr-2 h-4 w-4" />
                          Save
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => setIsEditingLesson(false)}
                        >
                          Cancel
                        </Button>
                      </div>
                    </div>
                  ) : (
                    <>
                      <h1 className="text-2xl font-bold">{selectedLesson.title}</h1>
                      {selectedLesson.description && (
                        <p className="text-muted-foreground mt-1">
                          {selectedLesson.description}
                        </p>
                      )}
                    </>
                  )}
                </div>
                {!isEditingLesson && (
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button variant="outline" size="icon">
                        <MoreVertical className="h-4 w-4" />
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                      <DropdownMenuItem onClick={() => setIsEditingLesson(true)}>
                        <Edit className="mr-2 h-4 w-4" />
                        Edit Lesson
                      </DropdownMenuItem>
                      <DropdownMenuSeparator />
                      <DropdownMenuItem
                        className="text-destructive"
                        onClick={handleDeleteLesson}
                      >
                        <Trash2 className="mr-2 h-4 w-4" />
                        Delete Lesson
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                )}
              </div>

              <Separator />

              {/* Lesson Items */}
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h2 className="font-semibold">Lesson Items</h2>
                    <p className="text-sm text-muted-foreground">
                      Drag to reorder. Select content from your library.
                    </p>
                  </div>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button>
                        <Plus className="mr-2 h-4 w-4" />
                        Add Item
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                      <DropdownMenuItem onClick={() => { setSelectedItemType("video"); setAddItemDialogOpen(true); }}>
                        <Video className="mr-2 h-4 w-4 text-primary" />
                        Add Video
                      </DropdownMenuItem>
                      <DropdownMenuItem onClick={() => { setSelectedItemType("rich-content"); setAddItemDialogOpen(true); }}>
                        <FileText className="mr-2 h-4 w-4 text-secondary" />
                        Add Rich Content
                      </DropdownMenuItem>
                      <DropdownMenuItem onClick={() => { setSelectedItemType("question"); setAddItemDialogOpen(true); }}>
                        <HelpCircle className="mr-2 h-4 w-4 text-warning" />
                        Add Question
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </div>

                {selectedLesson.items.length > 0 ? (
                  <Reorder.Group
                    axis="y"
                    values={selectedLesson.items}
                    onReorder={handleReorderItems}
                    className="space-y-2"
                  >
                    {selectedLesson.items
                      .sort((a, b) => a.order - b.order)
                      .map((item) => (
                        <Reorder.Item key={item.id} value={item}>
                          <Card className="hover:shadow-md transition-shadow">
                            <CardContent className="p-4">
                              <div className="flex items-center gap-3">
                                <div className="cursor-grab active:cursor-grabbing text-muted-foreground hover:text-foreground">
                                  <GripVertical className="h-5 w-5" />
                                </div>
                                <div className="p-2 rounded-lg bg-muted">
                                  {getItemIcon(item.type)}
                                </div>
                                <div className="flex-1 min-w-0">
                                  <p className="font-medium truncate">{item.name}</p>
                                  <p className="text-sm text-muted-foreground truncate">
                                    {getContentInfo(item)}
                                  </p>
                                </div>
                                <Badge variant="outline" className="capitalize text-xs">
                                  {item.type.replace("-", " ")}
                                </Badge>
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="text-muted-foreground hover:text-destructive"
                                  onClick={() => setDeleteItemId(item.id)}
                                >
                                  <X className="h-4 w-4" />
                                </Button>
                              </div>
                            </CardContent>
                          </Card>
                        </Reorder.Item>
                      ))}
                  </Reorder.Group>
                ) : (
                  <Card className="border-dashed">
                    <CardContent className="p-8 text-center">
                      <FileText className="h-12 w-12 mx-auto text-muted-foreground/50 mb-4" />
                      <h3 className="font-semibold mb-2">No items yet</h3>
                      <p className="text-sm text-muted-foreground mb-4">
                        Add content from your library to this lesson
                      </p>
                    </CardContent>
                  </Card>
                )}
              </div>
            </div>
          ) : (
            <div className="flex items-center justify-center h-full">
              <div className="text-center">
                <FileText className="h-16 w-16 mx-auto text-muted-foreground/50 mb-4" />
                <h3 className="font-semibold mb-2">Select a Lesson</h3>
                <p className="text-sm text-muted-foreground">
                  Choose a lesson from the sidebar to edit its content
                </p>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Add Content Dialog */}
      <Dialog open={addItemDialogOpen} onOpenChange={(open) => {
        if (!open) resetItemForm();
        setAddItemDialogOpen(open);
      }}>
        <DialogContent 
          className={cn(
            "max-h-[90vh] overflow-y-auto",
            selectedItemType === "video" && "sm:max-w-[900px]",
            selectedItemType === "rich-content" && "sm:max-w-[800px]",
            selectedItemType === "question" && "sm:max-w-[800px]"
          )}
          onPointerDownOutside={(e) => e.preventDefault()}
          onEscapeKeyDown={(e) => e.preventDefault()}
        >
          <DialogHeader>
            <DialogTitle>
              Add {selectedItemType === "video" ? "Video" : selectedItemType === "rich-content" ? "Rich Content" : "Question"}
            </DialogTitle>
            <DialogDescription>
              {selectedItemType === "video" && "Upload a video file or provide a URL"}
              {selectedItemType === "rich-content" && "Add text or HTML content"}
              {selectedItemType === "question" && "Create a multiple choice question"}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            {/* Common: Item Name */}
            <div className="space-y-2">
              <Label htmlFor="item-name">Name *</Label>
              <Input
                id="item-name"
                placeholder="Enter item name..."
                value={itemName}
                onChange={(e) => setItemName(e.target.value)}
              />
            </div>

            {/* Video Form */}
            {selectedItemType === "video" && (
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                {/* Left Column - Video Upload/Preview */}
                <div className="space-y-4">
                  {!videoFile ? (
                    <div
                      className="border-2 border-dashed rounded-lg p-8 text-center cursor-pointer hover:border-primary hover:bg-muted/50 transition-colors"
                      onDragOver={(e) => { e.preventDefault(); e.stopPropagation(); }}
                      onDrop={(e) => {
                        e.preventDefault();
                        e.stopPropagation();
                        const file = e.dataTransfer.files?.[0];
                        if (file) handleVideoFileSelect(file);
                      }}
                      onClick={() => {
                        const input = document.createElement('input');
                        input.type = 'file';
                        input.accept = 'video/mp4,video/webm,video/ogg,video/quicktime';
                        input.onchange = (e) => {
                          const file = (e.target as HTMLInputElement).files?.[0];
                          if (file) handleVideoFileSelect(file);
                        };
                        input.click();
                      }}
                    >
                      <div className="flex flex-col items-center gap-4">
                        <div className="w-16 h-16 rounded-full bg-muted flex items-center justify-center">
                          <Upload className="h-8 w-8 text-muted-foreground" />
                        </div>
                        <div>
                          <p className="font-medium">Drag and drop video files</p>
                          <p className="text-sm text-muted-foreground mt-1">
                            Or click to select a file
                          </p>
                        </div>
                        <Button type="button" variant="outline" size="sm">
                          <FileVideo className="h-4 w-4 mr-2" />
                          Select file
                        </Button>
                        <p className="text-xs text-muted-foreground">
                          MP4, WebM, MOV up to 500MB
                        </p>
                      </div>
                    </div>
                  ) : (
                    <div className="border rounded-lg overflow-hidden">
                      {/* Video Preview */}
                      <div className="relative aspect-video bg-black">
                        <video
                          src={videoPreviewUrl || undefined}
                          className="w-full h-full object-contain"
                          controls={videoUploadState === 'complete'}
                          muted
                        />
                        {videoUploadState !== 'complete' && (
                          <div className="absolute inset-0 bg-black/60 flex items-center justify-center">
                            <div className="text-center text-white">
                              {videoUploadState === 'uploading' && (
                                <>
                                  <Loader2 className="h-8 w-8 animate-spin mx-auto mb-2" />
                                  <p className="text-sm">Uploading... {videoUploadProgress}%</p>
                                </>
                              )}
                              {videoUploadState === 'processing' && (
                                <>
                                  <Settings className="h-8 w-8 animate-spin mx-auto mb-2" />
                                  <p className="text-sm">Processing video...</p>
                                </>
                              )}
                            </div>
                          </div>
                        )}
                        <Button
                          type="button"
                          variant="secondary"
                          size="icon"
                          className="absolute top-2 right-2"
                          onClick={removeVideoFile}
                        >
                          <X className="h-4 w-4" />
                        </Button>
                        {videoUploadState === 'complete' && videoDuration > 0 && (
                          <div className="absolute bottom-2 right-2 bg-black/70 text-white text-xs px-2 py-1 rounded">
                            {mediaStreamingService.formatDuration(videoDuration)}
                          </div>
                        )}
                      </div>

                      {/* Upload Progress */}
                      {videoUploadState === 'uploading' && (
                        <div className="p-3 border-t">
                          <Progress value={videoUploadProgress} className="h-1" />
                        </div>
                      )}

                      {/* Video Info */}
                      {videoUploadState === 'complete' && videoUploadResult && (
                        <div className="p-3 border-t space-y-2">
                          <div className="flex items-center justify-between">
                            <span className="text-xs text-muted-foreground">Video link</span>
                            <Button
                              type="button"
                              variant="ghost"
                              size="icon"
                              className="h-6 w-6"
                              onClick={() => {
                                navigator.clipboard.writeText(videoUploadResult.url);
                                toast({ title: "Copied!", description: "Video URL copied to clipboard" });
                              }}
                            >
                              <Copy className="h-3 w-3" />
                            </Button>
                          </div>
                          <p className="text-sm text-primary truncate">{videoUploadResult.url}</p>
                          <p className="text-xs text-muted-foreground">
                            {videoUploadResult.filename} • {mediaStreamingService.formatFileSize(videoUploadResult.size)}
                          </p>
                        </div>
                      )}
                    </div>
                  )}
                </div>

                {/* Right Column - Details */}
                <div className="space-y-4">
                  {/* Thumbnail Section */}
                  <div className="space-y-3">
                    <Label className="text-sm font-medium">Thumbnail</Label>
                    <p className="text-xs text-muted-foreground">
                      Set a thumbnail that stands out and draws viewers&apos; attention.
                    </p>
                    <div className="flex gap-2">
                      {/* Upload File Option */}
                      <div
                        className={cn(
                          "flex-1 border rounded-lg p-3 cursor-pointer transition-all hover:border-primary text-center",
                          thumbnailMode === 'upload' && "border-primary ring-1 ring-primary"
                        )}
                        onClick={() => {
                          const input = document.createElement('input');
                          input.type = 'file';
                          input.accept = 'image/jpeg,image/png,image/gif,image/webp';
                          input.onchange = (e) => {
                            const file = (e.target as HTMLInputElement).files?.[0];
                            if (file) handleThumbnailFileSelect(file);
                          };
                          input.click();
                        }}
                      >
                        {thumbnailPreviewUrl ? (
                          <img src={thumbnailPreviewUrl} alt="Thumbnail" className="w-full h-16 object-cover rounded mb-2" />
                        ) : (
                          <div className="w-full h-16 bg-muted rounded flex items-center justify-center mb-2">
                            <Upload className="h-4 w-4 text-muted-foreground" />
                          </div>
                        )}
                        <span className="text-xs">Upload file</span>
                      </div>

                      {/* Auto-generated Option */}
                      <div
                        className={cn(
                          "flex-1 border rounded-lg p-3 cursor-pointer transition-all hover:border-primary text-center",
                          thumbnailMode === 'auto' && "border-primary ring-1 ring-primary",
                          !autoGeneratedThumbnail && "opacity-50 cursor-not-allowed"
                        )}
                        onClick={() => autoGeneratedThumbnail && setThumbnailMode('auto')}
                      >
                        {autoGeneratedThumbnail ? (
                          <img src={autoGeneratedThumbnail} alt="Auto thumbnail" className="w-full h-16 object-cover rounded mb-2" />
                        ) : (
                          <div className="w-full h-16 bg-muted rounded flex items-center justify-center mb-2">
                            <Settings className="h-4 w-4 text-muted-foreground animate-pulse" />
                          </div>
                        )}
                        <span className="text-xs">Auto-generated</span>
                      </div>
                    </div>
                  </div>

                  <Separator />

                  {/* Duration display */}
                  {videoDuration > 0 && (
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-muted-foreground">Duration</span>
                      <span className="font-medium">{mediaStreamingService.formatDuration(videoDuration)}</span>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Rich Text Form */}
            {selectedItemType === "rich-content" && (
              <div className="space-y-2">
                <Label htmlFor="rich-content">Content *</Label>
                <Textarea
                  id="rich-content"
                  placeholder="Enter your text content here. HTML is supported..."
                  className="min-h-40"
                  value={richTextContent}
                  onChange={(e) => setRichTextContent(e.target.value)}
                />
                <p className="text-xs text-muted-foreground">
                  You can use HTML formatting for rich text
                </p>
              </div>
            )}

            {/* Question Form */}
            {selectedItemType === "question" && (
              <>
                <div className="space-y-2">
                  <Label htmlFor="question-text">Question *</Label>
                  <Textarea
                    id="question-text"
                    placeholder="Enter your question..."
                    value={questionText}
                    onChange={(e) => setQuestionText(e.target.value)}
                  />
                </div>
                <div className="space-y-2">
                  <Label>Answer Options</Label>
                  {questionOptions.map((option, index) => (
                    <div key={index} className="flex items-center gap-2">
                      <input
                        type="radio"
                        name="correct-option"
                        checked={correctOptionIndex === index}
                        onChange={() => setCorrectOptionIndex(index)}
                        className="h-4 w-4"
                      />
                      <Input
                        placeholder={`Option ${index + 1}`}
                        value={option}
                        onChange={(e) => {
                          const newOptions = [...questionOptions];
                          newOptions[index] = e.target.value;
                          setQuestionOptions(newOptions);
                        }}
                      />
                    </div>
                  ))}
                  <p className="text-xs text-muted-foreground">
                    Select the radio button next to the correct answer
                  </p>
                </div>
              </>
            )}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => {
              setAddItemDialogOpen(false);
              resetItemForm();
            }}>
              Cancel
            </Button>
            <Button 
              onClick={handleCreateItem}
              disabled={!itemName.trim() || 
                (selectedItemType === "video" && !videoUrl.trim()) ||
                (selectedItemType === "rich-content" && !richTextContent.trim()) ||
                (selectedItemType === "question" && (!questionText.trim() || questionOptions.filter(o => o.trim()).length < 2))
              }
            >
              <Plus className="mr-2 h-4 w-4" />
              Create {selectedItemType === "video" ? "Video" : selectedItemType === "rich-content" ? "Rich Content" : "Question"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Item Dialog */}
      <AlertDialog open={!!deleteItemId} onOpenChange={() => setDeleteItemId(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Remove Item</AlertDialogTitle>
            <AlertDialogDescription>
              Remove this item from the lesson? The content will remain in your library.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDeleteItem}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              Remove
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </AdminLayout>
  );
}
