using TAIF.Application.DTOs.Verification;
using TAIF.Domain.Entities;

namespace TAIF.Application.Interfaces.Services;

/// <summary>
/// Builds channel-specific, locale-aware messages from a user + OTP.
/// Replace the default implementation to change copy, add translations,
/// or pull templates from a database.
/// </summary>
public interface IVerificationTemplateProvider
{
    /// <param name="user">The recipient — used for personalisation (name, email, phone).</param>
    /// <param name="otp">The plain-text OTP generated by <see cref="IVerificationService"/>.</param>
    /// <param name="channel">The target channel name, e.g. "Email", "SMS".</param>
    /// <param name="locale">Optional BCP-47 locale tag, e.g. "ar", "en". Defaults to "en".</param>
    VerificationMessage Build(User user, string otp, string channel, string? locale = null);
}
