using Mapster;
using TAIF.Application.DTOs.Requests;
using TAIF.Application.DTOs.Responses;
using TAIF.Domain.Entities;
using static TAIF.Domain.Entities.Enums;

namespace TAIF.Application.Mappings
{
    /// <summary>
    /// Centralized Mapster mapping configuration for the application.
    /// Call <see cref="RegisterMappings"/> once at startup (e.g. in Program.cs) before any Adapt() calls.
    ///
    /// Convention for Ignored fields:
    ///   - Server-managed  : Id, CreatedAt, UpdatedAt, DeletedAt, IsDeleted, CreatedBy, UpdatedBy
    ///   - Org-scoped      : OrganizationId, Organization  (injected by the controller/service)
    ///   - Computed        : totals, statistics, aggregated values calculated by the server
    ///   - Security        : PasswordHash, RefreshToken, RefreshTokenExpiresAt, EmailVerified
    ///   - Navigation-only : collection/reference nav properties not populated from client input
    ///   - Manual          : fields set explicitly in services after Adapt<>() (e.g. Content, Order)
    /// </summary>
    public static class MappingConfig
    {
        public static void RegisterMappings()
        {
            // -------------------------------------------------------------------------
            // REQUEST  -->  ENTITY  (inbound: client payload to domain entity)
            // Only user-supplied fields are mapped; everything else is ignored so the
            // server stays in full control of audit, computed, and security fields.
            // -------------------------------------------------------------------------

            // CreateCourseRequest --> Course
            // Computed totals, status, and navigation properties are server-managed.
            TypeAdapterConfig<CreateCourseRequest, Course>.NewConfig()
                .Ignore(dest => dest.Status)                    // set to Draft by default; changed via dedicated endpoints
                .Ignore(dest => dest.TotalEnrolled)             // computed: incremented on each enrollment
                .Ignore(dest => dest.TotalDurationInSeconds)    // computed: sum of all lesson item durations
                .Ignore(dest => dest.TotalLessons)              // computed: count of assigned lessons
                .Ignore(dest => dest.TotalLessonItems)          // computed: count of all lesson items across lessons
                .Ignore(dest => dest.CourseLessons)             // navigation: managed via CourseLesson assignment endpoints
                .Ignore(dest => dest.Category)                  // navigation: resolved from CategoryId by EF
                .Ignore(dest => dest.Id)                        // server-managed: generated by the database
                .Ignore(dest => dest.CreatedAt)
                .Ignore(dest => dest.UpdatedAt)
                .Ignore(dest => dest.DeletedAt)
                .Ignore(dest => dest.IsDeleted)
                .Ignore(dest => dest.CreatedBy)
                .Ignore(dest => dest.UpdatedBy)
                .Ignore(dest => dest.OrganizationId)            // org-scoped: injected from the authenticated user's claim
                .Ignore(dest => dest.Organization);             // navigation: resolved from OrganizationId by EF

            // CreateLessonRequest --> Lesson
            // Computed totals and all navigation properties are ignored.
            TypeAdapterConfig<CreateLessonRequest, Lesson>.NewConfig()
                .Ignore(dest => dest.TotalDurationInSeconds)    // computed: recalculated when items are assigned
                .Ignore(dest => dest.TotalLessonItems)          // computed: count of assigned lesson items
                .Ignore(dest => dest.CourseLessons)             // navigation: managed via CourseLesson assignment endpoints
                .Ignore(dest => dest.LessonLessonItems)         // navigation: managed via LessonLessonItem assignment endpoints
                .Ignore(dest => dest.Instructor)                // navigation: resolved from InstructorId by EF
                .Ignore(dest => dest.Id)
                .Ignore(dest => dest.CreatedAt)
                .Ignore(dest => dest.UpdatedAt)
                .Ignore(dest => dest.DeletedAt)
                .Ignore(dest => dest.IsDeleted)
                .Ignore(dest => dest.CreatedBy)
                .Ignore(dest => dest.UpdatedBy)
                .Ignore(dest => dest.OrganizationId)
                .Ignore(dest => dest.Organization);

            // CreateLessonItemRequest --> LessonItem
            // ContentId is normalised: treat Guid.Empty as null so the FK is optional.
            TypeAdapterConfig<CreateLessonItemRequest, LessonItem>.NewConfig()
                .Map(dest => dest.ContentId,
                     src => src.ContentId == Guid.Empty ? (Guid?)null : src.ContentId)
                .Ignore(dest => dest.Content)                   // navigation: resolved from ContentId by EF
                .Ignore(dest => dest.LessonLessonItems)         // navigation: managed via LessonLessonItem assignment endpoints
                .Ignore(dest => dest.Id)
                .Ignore(dest => dest.CreatedAt)
                .Ignore(dest => dest.UpdatedAt)
                .Ignore(dest => dest.DeletedAt)
                .Ignore(dest => dest.IsDeleted)
                .Ignore(dest => dest.CreatedBy)
                .Ignore(dest => dest.UpdatedBy)
                .Ignore(dest => dest.OrganizationId)
                .Ignore(dest => dest.Organization);

            // CreateCategoryRequest --> Category
            TypeAdapterConfig<CreateCategoryRequest, Category>.NewConfig()
                .Ignore(dest => dest.Id)
                .Ignore(dest => dest.CreatedAt)
                .Ignore(dest => dest.UpdatedAt)
                .Ignore(dest => dest.DeletedAt)
                .Ignore(dest => dest.IsDeleted)
                .Ignore(dest => dest.CreatedBy)
                .Ignore(dest => dest.UpdatedBy)
                .Ignore(dest => dest.OrganizationId)
                .Ignore(dest => dest.Organization);

            // CreateTagRequest --> Tag
            TypeAdapterConfig<CreateTagRequest, Tag>.NewConfig()
                .Ignore(dest => dest.InterestMappings)          // navigation: populated separately via InterestTagMapping endpoints
                .Ignore(dest => dest.Id)
                .Ignore(dest => dest.CreatedAt)
                .Ignore(dest => dest.UpdatedAt)
                .Ignore(dest => dest.DeletedAt)
                .Ignore(dest => dest.IsDeleted)
                .Ignore(dest => dest.CreatedBy)
                .Ignore(dest => dest.UpdatedBy)
                .Ignore(dest => dest.OrganizationId)
                .Ignore(dest => dest.Organization);

            // RegisterRequest --> User
            // Role is explicitly mapped from the UserRoleType field on the request.
            // All security and server-managed fields are ignored.
            TypeAdapterConfig<RegisterRequest, User>.NewConfig()
                .Map(dest => dest.Role, src => src.UserRoleType) // explicit: enum field name differs between request and entity
                .Ignore(dest => dest.Id)
                .Ignore(dest => dest.PasswordHash)              // security: hashed separately before persisting
                .Ignore(dest => dest.IsActive)                  // server-managed: defaults to true on creation
                .Ignore(dest => dest.IsCompleted)               // server-managed: set after profile completion
                .Ignore(dest => dest.EmailVerified)             // server-managed: set after email verification flow
                .Ignore(dest => dest.RefreshToken)              // security: issued by the auth service
                .Ignore(dest => dest.RefreshTokenExpiresAt)     // security: set alongside RefreshToken
                .Ignore(dest => dest.Interests)                 // server-managed: set via the interests endpoint after registration
                .Ignore(dest => dest.OrganizationId)
                .Ignore(dest => dest.Organization)
                .Ignore(dest => dest.CreatedAt)
                .Ignore(dest => dest.UpdatedAt)
                .Ignore(dest => dest.DeletedAt)
                .Ignore(dest => dest.IsDeleted)
                .Ignore(dest => dest.CreatedBy)
                .Ignore(dest => dest.UpdatedBy);

            // CreateUserRequest --> User
            // Admin-side user creation; same security and server-managed exclusions as RegisterRequest.
            TypeAdapterConfig<CreateUserRequest, User>.NewConfig()
                .Ignore(dest => dest.Id)
                .Ignore(dest => dest.PasswordHash)              // security: hashed in UserController before persisting
                .Ignore(dest => dest.IsActive)                  // server-managed: set explicitly in the controller
                .Ignore(dest => dest.IsCompleted)               // server-managed: depends on the assigned role
                .Ignore(dest => dest.EmailVerified)             // server-managed: not verified on admin creation
                .Ignore(dest => dest.RefreshToken)
                .Ignore(dest => dest.RefreshTokenExpiresAt)
                .Ignore(dest => dest.Interests)
                .Ignore(dest => dest.OrganizationId)            // org-scoped: injected from the admin's org claim
                .Ignore(dest => dest.Organization)
                .Ignore(dest => dest.CreatedAt)
                .Ignore(dest => dest.UpdatedAt)
                .Ignore(dest => dest.DeletedAt)
                .Ignore(dest => dest.IsDeleted)
                .Ignore(dest => dest.CreatedBy)
                .Ignore(dest => dest.UpdatedBy);

            // -------------------------------------------------------------------------
            // ENTITY  -->  RESPONSE  (outbound: domain entity to API response DTO)
            // -------------------------------------------------------------------------

            // User --> UserResponse
            // RoleName is the string representation of the Role enum for readability.
            // UserRoleType is kept as the numeric enum for client-side comparisons.
            // OrganizationName is flattened from the Organization navigation property.
            TypeAdapterConfig<User, UserResponse>.NewConfig()
                .Map(dest => dest.RoleName, src => src.Role.ToString())
                .Map(dest => dest.UserRoleType, src => src.Role)
                .Map(dest => dest.OrganizationName,
                     src => src.Organization != null ? src.Organization.Name : null);

            // LessonItem --> LessonItemResponse
            // Content  : requires JSON deserialization into a typed object — set manually
            //            after Adapt<>() in LessonItemService and LessonItemProgressService.
            // Order    : lives on LessonLessonItem (junction table), not on LessonItem itself —
            //            set manually from the junction record after Adapt<>().
            // IsCompleted : user-specific progress state — set manually from the progress
            //               lookup in LessonItemProgressService.GetLessonItemsProgressAsync().
            TypeAdapterConfig<LessonItem, LessonItemResponse>.NewConfig()
                .Ignore(dest => dest.Content)
                .Ignore(dest => dest.Order)
                .Ignore(dest => dest.IsCompleted);

            // LessonLessonItem --> LessonLessonItemResponse
            // Flattens the linked LessonItem's display fields into the junction response.
            TypeAdapterConfig<LessonLessonItem, LessonLessonItemResponse>.NewConfig()
                .Map(dest => dest.LessonItemName,
                     src => src.LessonItem != null ? src.LessonItem.Name : null)
                .Map(dest => dest.LessonItemType,
                     src => src.LessonItem != null ? (int?)src.LessonItem.Type : null);

            // Course --> CourseResponse
            // Tags is ICollection<Guid> on the entity; materialise it to List<Guid> for the response.
            // Rating (AverageRating) is NOT mapped here — it is enriched post-Adapt in
            // CourseController.EnrichWithReviewStatsAsync() via the review statistics service.
            TypeAdapterConfig<Course, CourseResponse>.NewConfig()
                .Map(dest => dest.Tags, src => src.Tags.ToList());

            // Lesson --> LessonResponse
            // Instructor is conditionally mapped to InstructorResponse only when the
            // navigation property is loaded (requires ThenInclude in the repository query).
            TypeAdapterConfig<Lesson, LessonResponse>.NewConfig()
                .Map(dest => dest.Instructor,
                     src => src.Instructor != null ? src.Instructor.Adapt<InstructorResponse>() : null);

            // Content --> ContentResponse
            // Exposes only safe fields (no IsDeleted, audit fields, or the [NotMapped] ContentData property).
            TypeAdapterConfig<Content, ContentResponse>.NewConfig();

            // Flat mappings — no custom logic required; Mapster handles name/type matching automatically.
            TypeAdapterConfig<Organization, OrganizationResponse>.NewConfig();
            TypeAdapterConfig<Category, CategoryResponse>.NewConfig();
            TypeAdapterConfig<Tag, TagResponse>.NewConfig();
            TypeAdapterConfig<Interest, InterestResponse>.NewConfig();
            TypeAdapterConfig<InterestTagMapping, InterestTagMappingResponse>.NewConfig();
            TypeAdapterConfig<Enrollment, EnrollmentResponse>.NewConfig();
            TypeAdapterConfig<LessonItemProgress, LessonItemProgressResponse>.NewConfig();
            TypeAdapterConfig<UserLearningPathProgress, UserLearningPathProgressResponse>.NewConfig();
            TypeAdapterConfig<LearningPath, LearningPathResponse>.NewConfig();
            TypeAdapterConfig<LearningPathSection, LearningPathSectionResponse>.NewConfig();
            TypeAdapterConfig<LearningPathCourse, LearningPathCourseResponse>.NewConfig();
            TypeAdapterConfig<CourseLesson, CourseLessonResponse>.NewConfig();
            TypeAdapterConfig<Instructor, InstructorResponse>.NewConfig();
        }
    }
}